#!/usr/bin/env bash
# Create a run configuration for the short adaptation fine-tune.
#
# Usage:
#   bash scripts/create_objectplacement_overnight_config.sh

set -euo pipefail

OUT_FILE="$(pwd)/configs/objectplacement_overnight.env"
mkdir -p "$(dirname "$OUT_FILE")"

cat > "$OUT_FILE" <<'EOF'
# ObjectPlacement adaptation config (auto-generated)
# Generated by scripts/create_objectplacement_overnight_config.sh

# Remote workstation
WORKSTATION_SSH_HOST="nr@10.15.146.156"

# Task and model choices
DATASET_NAME="G1_Dex3_ObjectPlacement_Dataset"
BASE_CHECKPOINT="UnifoLM-VLA-Base"

# Modality settings
HEAD_CAMERA_ONLY="true"
USE_CAM_LEFT_HIGH="true"
USE_CAM_RIGHT_HIGH="true"
USE_CAM_LEFT_WRIST="false"
USE_CAM_RIGHT_WRIST="false"

# Training budget
RUN_MODE="overnight"
TARGET_HOURS="10"

# Eval goals
PRIMARY_METRIC="task_success_rate_on_robot"
FIRST_EVAL_IN_HARNESS="true"

# Robot control interface (fill after running baseline collection script)
ROBOT_IP="192.168.123.164"
ROBOT_NET_INTERFACE=""
DEX3_SERVICE_COMMAND=""
ROBOT_CLIENT_COMMAND="python scripts/robot_client.py --robot_type g1_dex3"

# Paths (edit as needed)
VLA_REPO_DIR="$HOME/unifolm-vla"
WMA_DEPLOY_REPO_DIR="$HOME/unifolm-world-model-action"
DATA_DIR="$HOME/data/G1_Dex3_ObjectPlacement_Dataset"
CHECKPOINT_DIR="$HOME/checkpoints/UnifoLM-VLA-Base"
OUTPUT_DIR="$HOME/experiments/objectplacement_headcam_overnight"
EOF

echo "Created $OUT_FILE"
echo "Next steps:"
echo "1) Run baseline collector: bash scripts/collect_remote_baseline_and_interface.sh"
echo "2) Fill ROBOT_NET_INTERFACE and DEX3_SERVICE_COMMAND in $OUT_FILE"
echo "3) Start overnight training using this config."
